apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-controller
  name: vault-controller
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vault-controller
